# general settings
name: HAT_ImageNet_Pretrain
model_type: SwinIRMSModel
scale: 1
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: ImageNet
    type: RandomScaleDownsampleImageDataset
    random_scales: [2, 3, 4]
    dataroot_gt: /home2/leedh97/datasets/imagenet_flatten
    filename_tmpl: '{}'
    io_backend:
      type: disk

    lq_size: 64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: Set14X2
    type: FixedScalePairedImageDataset
    dataroot_gt: /home2/prof/ro/dslisleedh/SAFMN/datasets/Set14/HR
    dataroot_lq: /home2/prof/ro/dslisleedh/SAFMN/datasets/Set14/LR_bicubic/X2
    filename_tmpl: '{}x2'
    ds_scale: 2
    io_backend:
      type: disk

  val_2:
    name: Set14X4
    type: FixedScalePairedImageDataset
    dataroot_gt: /home2/prof/ro/dslisleedh/SAFMN/datasets/Set14/HR
    dataroot_lq: /home2/prof/ro/dslisleedh/SAFMN/datasets/Set14/LR_bicubic/X4
    filename_tmpl: '{}x4'
    ds_scale: 4
    io_backend:
      type: disk

# network structures
network_g:
  type: HAT
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'igconv+igsample'
  resi_connection: '1conv'
  return_skip: false
  geo_ensemble: true

print_network: true
# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000, 500000, 650000, 700000, 750000]
    gamma: 0.5

  total_iter: 800000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
