# general settings
name: SMFANet_IG_DF2K
model_type: MSRModel
scale: 1
num_gpu: 4
manual_seed: 0


# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: RandomScaleDownsampleImageDataset
    random_scales: [2, 3, 4]
    dataroot_gt: /home2/leedh97/datasets/DF2K/DF2K_train_HR_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    lq_size: 64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    # prefetch_mode: ~
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: Urban100X2
    type: FixedScalePairedImageDataset
    dataroot_gt: /home2/prof/ro/dslisleedh/SAFMN/datasets/Urban100/HR
    dataroot_lq: /home2/prof/ro/dslisleedh/SAFMN/datasets/Urban100/LR_bicubic/X2
    filename_tmpl: '{}x2'
    ds_scale: 2
    io_backend:
      type: disk

  val_2:
    name: Urban100X3
    type: FixedScalePairedImageDataset
    dataroot_gt: /home2/prof/ro/dslisleedh/SAFMN/datasets/Urban100/HR
    dataroot_lq: /home2/prof/ro/dslisleedh/SAFMN/datasets/Urban100/LR_bicubic/X3
    filename_tmpl: '{}x3'
    ds_scale: 3
    io_backend:
      type: disk  

  val_3:
    name: Urban100X4
    type: FixedScalePairedImageDataset
    dataroot_gt: /home2/prof/ro/dslisleedh/SAFMN/datasets/Urban100/HR
    dataroot_lq: /home2/prof/ro/dslisleedh/SAFMN/datasets/Urban100/LR_bicubic/X4
    filename_tmpl: '{}x4'
    ds_scale: 4
    io_backend:
      type: disk

# network structures
network_g:
  type: SMFANetIG
  dim: 48
  n_blocks: 12
  ffn_scale: 2
  upscaling_factor: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-6

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:  # original SMFANet uses FFTLoss
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: False
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500